import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f0f0f0",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        height: 60,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
        paddingLeft: 16,
    },
    titleContainer: {
        marginLeft: 16,
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
    },
    subtitle: {
        fontSize: 14,
        color: "#666",
    },
    searchBar: {
        flexDirection: "row",
        alignItems: "center",
        margin: 16,
        paddingLeft: 16,
        backgroundColor: "#e0e0e0",
        borderRadius: 8,
    },
    searchInput: {
        flex: 1,
        marginLeft: 8,
        fontSize: 16,
        color: "#333",
    },
    quickActions: {
        flexDirection: "row",
        justifyContent: "space-around",
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
        backgroundColor: "#fff",
        marginBottom: 8,
    },
    actionItem: {
        alignItems: "center",
    },
    actionIcon: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#e0e0e0",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    addBadge: {
        position: "absolute",
        top: 0,
        right: 0,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: "#333",
        justifyContent: "center",
        alignItems: "center",
    },
    addText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "bold",
    },
    actionText: {
        marginTop: 8,
        fontSize: 14,
        color: "#333",
    },
    section: {
        paddingHorizontal: 16,
        paddingTop: 16,
        backgroundColor: "#fff",
        marginBottom: 8,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 12,
    },
    contactItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    contactInfo: {
        flexDirection: "row",
        alignItems: "center",
    },
    avatarContainer: {
        position: "relative",
    },
    avatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
    verifiedBadge: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: "orange",
        justifyContent: "center",
        alignItems: "center",
    },
    memberCountBadge: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: "#888",
        justifyContent: "center",
        alignItems: "center",
    },
    memberCountText: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "bold",
    },
    contactName: {
        marginLeft: 12,
        fontSize: 16,
        color: "#333",
    },
    checkCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e0e0e0",
        justifyContent: "center",
        alignItems: "center",
    },
    innerCheck: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: "#0084ff",
    },
});
  