export const ROUTING = {
    HOME: 'home',
    LOGIN: 'Login',
    REGISTER: 'Register',
    SEARCH: 'search',
    CHAT_LIST_SCREEN: 'ChatList',
    DIARY_SCREEN: 'Diary',
    PROFILE_SCREEN: 'Profile',
    CONTACTS_SCREEN: 'Contacts',
    DISCOVERY_SCREEN: 'Discovery',
    SEARCH_SCREEN: 'Tìm kiếm',
    CHAT_SCREEN: 'ChatScreen',
    PROFILE: 'ProfileDetail',
    QR: 'QR',
    QR_SCAN: 'QR_SCAN',
    CHANGE_PASSWORD: 'ChangePassword',
    UPDATE_PROFILE: 'UpdateProfile',
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    TAB_WITH_HEADER_NAVIGATION: 'TabWithHeaderNavigator',
    OPTION_SCREEN: 'Option',
    GROUP_SCREEN: 'Group',
    FRIEND_REQUEST_SCREEN: 'Request',
    PROFILE_USER_SCREEN: 'ProfileUser',
};