export const ROUTING = {
    HOME: 'home',
    LOGIN: 'Login',
    REGISTER: 'Tạo tài khoản',
    SEARCH: 'search',
    CHAT_LIST_SCREEN: 'Tin nhắn',
    DIARY_SCREEN: 'Nhật ký',
    PROFILE_SCREEN: 'Cá nhân',
    CONTACTS_SCREEN: 'Danh bạ',
    DISCOVERY_SCREEN: 'Khám phá',
    SEARCH_SCREEN: 'Tìm kiếm',
    CHAT_SCREEN: 'ChatScreen',
    PROFILE: 'Profile',
    QR: 'QR',
    QR_SCAN: 'QR_SCAN',
    CHANGE_PASSWORD: 'Đổi mật khẩu',
    UPDATE_PROFILE: 'Cập nhật thông tin cá nhân',
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    TAB_WITH_HEADER_NAVIGATION: 'TabWithHeaderNavigator',
};