import { ROUTING } from "@/utils/constant";
export type RootStackParamList = {
    [ROUTING.HOME]: undefined;
    [ROUTING.LOGIN]: undefined;
    [ROUTING.REGISTER]: undefined;
    [ROUTING.TAB_WITH_HEADER_NAVIGATION]: undefined;
    [ROUTING.CONTACTS_SCREEN]: undefined;
    [ROUTING.DISCOVERY_SCREEN]: undefined;
    [ROUTING.PROFILE_SCREEN]: undefined;
    [ROUTING.DIARY_SCREEN]: undefined;
    [ROUTING.CHAT_LIST_SCREEN]: undefined;
    [ROUTING.SEARCH_SCREEN]: undefined;
    [ROUTING.CHAT_SCREEN]: { item: any };
    [ROUTING.PROFILE]: undefined;
    [ROUTING.FORGOT_PASSWORD]: undefined;
    [ROUTING.RESET_PASSWORD]: { email: string };
    [ROUTING.QR]: undefined;
    [ROUTING.QR_SCAN]: undefined;
    [ROUTING.CHANGE_PASSWORD]: undefined;
    [ROUTING.UPDATE_PROFILE]: undefined;
    [ROUTING.GROUP_SCREEN]: undefined;
    [ROUTING.FRIEND_REQUEST_SCREEN]: undefined;
    [ROUTING.PROFILE_FRIEND_SCREEN]: { itemFriend: any };
    [ROUTING.OPTION_GROUP]: { itemGroup: any };
    [ROUTING.OPTION_FRIEND]: { itemFriend: any };
    [ROUTING.MEMBER_MANAGEMENT_SCREEN]: { itemGroup: any };
    [ROUTING.ADD_TO_GROUP]: { itemGroup: any };
    [ROUTING.FORWARD_MESSAGE]: { item: any; onClose: () => void; selectedMessage: any };
};